### ISSUE TITLE
Options market task list

### ISSUE THREAD

**Issue by razi90** [razi90/community-scrypto#1]
### Design
- [ ] Sequence diagram for 'Provide Liquidity' and 'Remove Liquidity'
- [ ] Activity diagram
- [ ] Class (blueprint) diagram

### Test
- [ ] Buy option
- [ ] Exercise option
- [ ] Provide liquidity
- [ ] Remove liquidity
- [ ] Pay LPs with premium

### Implementation
- [ ] Implement prototype with one market
